apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: default
  labels:
    k8s-app: fluent-bit
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush                     5
        Log_Level                 info
        Daemon                    off
        Parsers_File              parsers.conf


    @INCLUDE application-log.conf

  application-log.conf: |
    [INPUT]
        Name                tail
        Path                /log/*.log
        Mem_Buf_Limit       5MB
        Refresh_Interval    10

    [FILTER]
        name                grep
        match               *

    [OUTPUT]
        Name                cloudwatch_logs
        Match               *
        region              ap-southeast-1
        log_stream_prefix   ${HOSTNAME}
        log_group_name      sit-helloworld-go-application
        auto_create_group   true

  parsers.conf: |
    [PARSER]
        Name                tomcat
        match               *
